CLASS zcl_arm_eml_test_auto DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zcl_arm_eml_test_auto  IMPLEMENTATION.
ENDCLASS.
